[package]
name = "dezswap"
version = "1.2.0"
authors = ["DELIGHT LABS"]
edition = "2018"
description = "Common dezswap types"
license = "Apache-2.0"
repository = "https://github.com/dezswap/dezswap-contracts"
homepage = "https://dezswap.io"
documentation = "https://docs.dezswap.io"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
cw2 = { version = "2.0.0" } 
cw20 = { version = "2.0.0" } 
cosmwasm-std = { version = "2.2.2", features = ["cosmwasm_2_0"] }
protobuf = { version = "2", features = ["with-bytes"] }
cosmwasm-schema = { version = "2.2.0" }
serde_json = "1.0.141"

[profile.release]
opt-level = 3
debug = false
rpath = false
lto = true
debug-assertions = false
codegen-units = 1
panic = 'abort'
incremental = false
overflow-checks = true
